//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventRater.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventRater.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarity.
        /// </summary>
        public static string Clarity {
            get {
                return ResourceManager.GetString("Clarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key points made clearly and without unnecessary details.
        /// </summary>
        public static string ClarityDesc {
            get {
                return ResourceManager.GetString("ClarityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter event code.
        /// </summary>
        public static string EnterEventCode {
            get {
                return ResourceManager.GetString("EnterEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid event code..
        /// </summary>
        public static string EnterValidEventCode {
            get {
                return ResourceManager.GetString("EnterValidEventCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send your feedback. Please try later..
        /// </summary>
        public static string FeedbackFail {
            get {
                return ResourceManager.GetString("FeedbackFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback has been successfuly sent. Thank you..
        /// </summary>
        public static string FeedbackSent {
            get {
                return ResourceManager.GetString("FeedbackSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture method.
        /// </summary>
        public static string LectureMethod {
            get {
                return ResourceManager.GetString("LectureMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relevance, coverage of subject.
        /// </summary>
        public static string LectureMethodDesc {
            get {
                return ResourceManager.GetString("LectureMethodDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference not found. Please enter a valid event code..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process code. Please try later..
        /// </summary>
        public static string ProcessFail {
            get {
                return ResourceManager.GetString("ProcessFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND FEEDBACK.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker&apos;s knowledge.
        /// </summary>
        public static string SpeakerKnowledge {
            get {
                return ResourceManager.GetString("SpeakerKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spearker&apos;s style.
        /// </summary>
        public static string SpeakerStyle {
            get {
                return ResourceManager.GetString("SpeakerStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suitability.
        /// </summary>
        public static string Suitability {
            get {
                return ResourceManager.GetString("Suitability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminology and technical details suitable to audience.
        /// </summary>
        public static string SuitabilityDesc {
            get {
                return ResourceManager.GetString("SuitabilityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open voting page. Please try later..
        /// </summary>
        public static string VotingFail {
            get {
                return ResourceManager.GetString("VotingFail", resourceCulture);
            }
        }
    }
}
